/**
 * Phase A — aggregate.ts
 *
 * Reads the CSV file generated by generate.ts using Node.js Readable streams,
 * then computes per-sensor statistics:
 *   - count, min, max, average for temperature, humidity, and pressure
 *
 * Usage:
 *   npx ts-node src/phase-a/aggregate.ts
 *   npm run aggregate
 *
 * NOTE: Run `npm run generate` first to create the CSV file.
 */

import fs from 'fs';
import path from 'path';
import readline from 'readline';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface SensorStats {
  count: number;
  temperature: FieldStats;
  humidity: FieldStats;
  pressure: FieldStats;
}

interface FieldStats {
  sum: number;
  min: number;
  max: number;
}

type AggregationMap = Map<string, SensorStats>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function createFieldStats(): FieldStats {
  return { sum: 0, min: Infinity, max: -Infinity };
}

function createSensorStats(): SensorStats {
  return {
    count: 0,
    temperature: createFieldStats(),
    humidity: createFieldStats(),
    pressure: createFieldStats(),
  };
}

/** Updates a FieldStats record with a new value. */
function updateField(stats: FieldStats, value: number): void {
  stats.sum += value;
  if (value < stats.min) stats.min = value;
  if (value > stats.max) stats.max = value;
}

/** Parses a single CSV line (skipping the header). Returns null if invalid. */
function parseLine(
  line: string,
  lineNumber: number,
): { sensorId: string; temperature: number; humidity: number; pressure: number } | null {
  const parts = line.split(',');

  if (parts.length < 6) {
    console.warn(`  [warn] Line ${lineNumber}: expected 6 columns, got ${parts.length} — skipped`);
    return null;
  }

  const [, sensorId, , rawTemp, rawHumid, rawPressure] = parts;

  const temperature = parseFloat(rawTemp);
  const humidity = parseFloat(rawHumid);
  const pressure = parseFloat(rawPressure);

  if ([temperature, humidity, pressure].some(isNaN)) {
    console.warn(`  [warn] Line ${lineNumber}: non-numeric value — skipped`);
    return null;
  }

  return { sensorId, temperature, humidity, pressure };
}

// ---------------------------------------------------------------------------
// Stream aggregator
// ---------------------------------------------------------------------------

async function aggregateCsv(filePath: string): Promise<AggregationMap> {
  return new Promise((resolve, reject) => {
    if (!fs.existsSync(filePath)) {
      reject(
        new Error(
          `CSV file not found: ${filePath}\nRun "npm run generate" first.`,
        ),
      );
      return;
    }

    const aggregation: AggregationMap = new Map();
    const fileStream = fs.createReadStream(filePath, { encoding: 'utf-8' });
    const rl = readline.createInterface({ input: fileStream, crlfDelay: Infinity });

    let lineNumber = 0;
    let totalRows = 0;
    let skippedRows = 0;

    rl.on('line', (line) => {
      lineNumber++;

      // Skip header
      if (lineNumber === 1) return;

      const parsed = parseLine(line, lineNumber);
      if (!parsed) {
        skippedRows++;
        return;
      }

      const { sensorId, temperature, humidity, pressure } = parsed;

      if (!aggregation.has(sensorId)) {
        aggregation.set(sensorId, createSensorStats());
      }

      const stats = aggregation.get(sensorId)!;
      stats.count++;
      updateField(stats.temperature, temperature);
      updateField(stats.humidity, humidity);
      updateField(stats.pressure, pressure);

      totalRows++;
    });

    rl.on('close', () => {
      console.log(`\nStreamed ${lineNumber - 1} data rows (${skippedRows} skipped).`);
      resolve(aggregation);
    });

    rl.on('error', reject);
    fileStream.on('error', reject);
  });
}

// ---------------------------------------------------------------------------
// Report printer
// ---------------------------------------------------------------------------

function printReport(aggregation: AggregationMap): void {
  console.log('\n========================================');
  console.log('  Sensor Aggregation Report');
  console.log('========================================\n');

  const sortedSensors = [...aggregation.keys()].sort();

  for (const sensorId of sortedSensors) {
    const stats = aggregation.get(sensorId)!;

    const avgTemp = (stats.temperature.sum / stats.count).toFixed(2);
    const avgHumid = (stats.humidity.sum / stats.count).toFixed(2);
    const avgPressure = (stats.pressure.sum / stats.count).toFixed(2);

    console.log(`Sensor: ${sensorId}  (${stats.count} readings)`);
    console.log(
      `  Temperature : min=${stats.temperature.min.toFixed(2)}°C  max=${stats.temperature.max.toFixed(2)}°C  avg=${avgTemp}°C`,
    );
    console.log(
      `  Humidity    : min=${stats.humidity.min.toFixed(2)}%   max=${stats.humidity.max.toFixed(2)}%   avg=${avgHumid}%`,
    );
    console.log(
      `  Pressure    : min=${stats.pressure.min.toFixed(2)} hPa  max=${stats.pressure.max.toFixed(2)} hPa  avg=${avgPressure} hPa`,
    );
    console.log();
  }

  console.log('========================================\n');
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const csvPath = path.join(__dirname, 'data', 'sensor_readings.csv');

  console.log(`Aggregating: ${csvPath}`);

  try {
    const aggregation = await aggregateCsv(csvPath);
    printReport(aggregation);
  } catch (err) {
    console.error('Error:', (err as Error).message);
    process.exit(1);
  }
}

main();
